name: Readinglist Flat-data sync
on:
  push:
    paths-ignore:
        - "BookNotes/*"
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron:  '0 13 * * 1'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      # This step installs Deno, which is a new Javascript runtime that improves on Node. Can be used for an optional postprocessing step
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.10.x
      # Check out the repository so it can read the files inside of it and do other operations
      - name: Check out repo
        uses: actions/checkout@v4
      # The Flat Action step. We fetch the data in the http_url and save it as downloaded_filename
      - name: Fetch Backlog
        uses: githubocto/flat@v3
        with:
          http_url: ${{ secrets.READINGLIST_URL }}/backlogList
          downloaded_filename: backlog.json
          mask: '["${{ secrets.READINGLIST_URL }}"]'
          postprocess: postprocess.js

      - name: Fetch Reading
        uses: githubocto/flat@v3
        with:
          http_url: ${{ secrets.READINGLIST_URL }}/readingList
          downloaded_filename: reading.json
          mask: '["${{ secrets.READINGLIST_URL }}"]'
          postprocess: postprocess.js

      - name: Fetch Done
        uses: githubocto/flat@v3
        with:
          http_url: ${{ secrets.READINGLIST_URL }}/doneList
          downloaded_filename: done.json
          mask: '["${{ secrets.READINGLIST_URL }}"]'
          postprocess: postprocess.js
